name: pdfize

on: [push, pull_request]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: ${{ github.head_ref }}
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=README.pdf README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create PDF automagically using pandoc
