name: pdfize

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: sudo apt update && sudo apt-get install apt-file
      - run: sudo apt-file search adjustbox.sty
      - uses: docker://pandoc/latex:2.9
        with:
          args: README.md --output=README.pdf --template trivadis.tex
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create PDF automagically using pandoc
